### PR TITLE
Split gateway

### PR DESCRIPTION
**Pull request by will-moore**
While running `futurize` &c. on `omero/gateway/__init__.py` unicode errors were being thrown. In order to help identify the cause, this tackles the long-outstanding issue of line count in that file by splitting the gateway into multiple modules.

At the moment, the design is such that all of the new modules get re-imported into omero.gateway so that an end user would not notice the difference. Eventually we should deprecated that usage.

This is working now for me in manual testing of webclient and in almost all ```test/integration/gateway_test/``` (except those marked as broken and 1 performance test).

(This replaces @joshmoore's branch of the same name https://github.com/ome/omero-py/pull/7)

### CODE REVIEW

**Comment by will-moore** [comment]
Training test  https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-training/140/console failing with

```
02:14:42   File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
02:14:42     "__main__", fname, loader, pkg_name)
02:14:42   File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
02:14:42     exec code in run_globals
02:14:42   File "/home/omero/workspace/OMERO-training/openmicroscopy/examples/Training/python/__main__.py", line 24, in <module>
02:14:42     execfile(os.path.join(training_dir, 'Render_Images.py'))
02:14:42   File "/home/omero/workspace/OMERO-training/openmicroscopy/examples/Training/python/Render_Images.py", line 85, in <module>
02:14:42     image.setActiveChannels(channels, colors=color_list)
02:14:42   File "/home/omero/workspace/OMERO-training/OMERO.py/lib/python/omero/gateway/_images.py", line 839, in wrapped
02:14:42     return f(self, *args, **kwargs)
02:14:42   File "/home/omero/workspace/OMERO-training/OMERO.py/lib/python/omero/gateway/_images.py", line 1758, in setActiveChannels
02:14:42     invertMaps, reverseMaps, False)
02:14:42   File "/home/omero/workspace/OMERO-training/OMERO.py/lib/python/omero/gateway/_images.py", line 839, in wrapped
02:14:42     return f(self, *args, **kwargs)
02:14:42   File "/home/omero/workspace/OMERO-training/OMERO.py/lib/python/omero/gateway/_images.py", line 1742, in set_active_channels
02:14:42     rgba = splitHTMLColor(colors[idx])
02:14:42 NameError: global name 'splitHTMLColor' is not defined
0
```

**Comment by manics** [comment]
No idea if this is related, but clicking on an image in OMERO.web on today's merge-ci leads to an error.... but the feedback dialog isn't displayed as it uses a `http` URL when merge-ci is under `https`

**Comment by joshmoore** [comment]
Temporarily excluding to see if I can get https://github.com/ome/omero-py/pull/19 to pass. Happy to deal with the conflicts in either of the PRs.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#56](https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/56/). See the [console output](https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/56/consoleText) for more details.
Possible conflicts:
  - PR #19 joshmoore 'Py3 (1)'
    - src/omero/gateway/__init__.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#57](https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/57/). See the [console output](https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/57/consoleText) for more details.
Possible conflicts:
  - PR #19 joshmoore 'Py3 (1)'
    - src/omero/gateway/__init__.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#50](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/50/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-python-superbuild-push/50/consoleText) for more details.
Possible conflicts:
  - PR #19 joshmoore 'Py3 (1)'
    - src/omero/gateway/__init__.py

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-python-superbuild-push#18](https://idr1-slot3.openmicroscopy.org:48443/jenkins/job/OMERO-python-superbuild-push/18/). See the [console output](https://idr1-slot3.openmicroscopy.org:48443/jenkins/job/OMERO-python-superbuild-push/18/consoleText) for more details.
Possible conflicts:
  - PR #19 joshmoore 'Py3 (1)'
    - src/omero/gateway/__init__.py

--conflicts

**Pull request closed without merging**
