### PR TITLE
plugins: obj

### PR DESCRIPTION
**Pull request by jburel**
Message no longer exists
Print the error instead

* https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/29/testReport/OmeroPy.test.integration.clitest.test_obj/TestObj/test_get_unknown_and_empty_field/
* https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/29/testReport/OmeroPy.test.integration.clitest.test_obj/TestObj/test_list_get/

### CODE REVIEW

**Comment by joshmoore** [comment]
Is there a change in the output for the user? One option would be to access the message via `args`: https://portingguide.readthedocs.io/en/latest/exceptions.html#iterating-exceptions

**Comment by joshmoore** [comment]
https://github.com/ome/openmicroscopy/pull/6144/files#diff-963231c1845e662ac0e67d218bcf118eR102 suggests that there is _no_ change in the output?

**Comment by jburel** [comment]
I did not notice any changes. I could use ``args`` as suggested in the guide if we prefer

**Comment by jburel** [comment]
Read message from args as suggested in the porting guide

**Comment by jburel** [comment]
The 2 tests listed in the description should still be green in both py2 and 3

**Comment by joshmoore** [comment]
Both tests pass in merge (224) and py3 (40)

**Pull request merged**
