### PR TITLE
Remove omero_ext.argparse

### PR DESCRIPTION
**Pull request by manics**
See https://github.com/ome/omero-py/pull/110

~~This will conflict~~ rebased

--exclude see https://github.com/ome/omero-py/pull/115#pullrequestreview-322991815

### CODE REVIEW

**Comment by joshmoore** [comment]
```
E           Exception: Missing prompt: 'Server: [localhost:4064]'
```
etc.

**Comment by manics** [comment]
I'm still no nearer to finding out what's happening.

**Comment by sbesson** [comment]
The last two commits fix the upstream conflicts following the inclusion of #123 and the failing unit tests (33f0017). It looks like the upstream `argparse` enforces positional arguments to be appended to the command.

This should be ready for re-inclusion in the daily builds and a round of CLI review.

In terms of API, is there a way to have `omero_ext.argparse` simply alias the upstream `argparse` library and deprecate it?

**Comment by joshmoore** [comment]
> It looks like the upstream `argparse` enforces positional arguments

This will have a pretty wide impact. e.g. `bin/omero -s localhost login` is pretty common.

**Comment by sbesson** [comment]
> This will have a pretty wide impact. e.g. bin/omero -s localhost login is pretty common.

Agreed, I am pretty certain all the CLI integration tests are appending the command to the login arguments for instance. Probably worth looking into an option to maintain some backwards compatibility.

**Pull request closed without merging**
