### PR TITLE
Tox: Python 3.8, use travis bionic ice-py wheels

### PR DESCRIPTION
**Pull request by manics**
- [x] Requires https://github.com/manics/zeroc-ice-py-travis-bionic/releases/tag/0.0.1

--exclude
Conflicts with https://github.com/ome/omero-py/pull/162

### CODE REVIEW

**Comment by joshmoore** [comment]
Shall we migrate the repo before moving forward?

**Comment by manics** [comment]
Initiated! I thought people would prefer to see an example of it in use before adding our 288th repo 😀

**Comment by joshmoore** [comment]
> Initiated!

https://github.com/ome/zeroc-ice-py-travis-bionic

**Comment by joshmoore** [comment]
<details>
<summary>
Restarting Py36 due to HDF5 failure
</summary>

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/unit/tablestest/test_servants.py:352: in testTableAddData
    template = table.getHeaders(self.current)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
args = (object #0 (::omero::grid::Table)
{
}, <test_servants.mock_current object at 0x7f74cd047e10>)
kwargs = {}, self = object #0 (::omero::grid::Table)
{
}
msg = 'Traceback (most recent call last):\n  File "/home/travis/build/ome/omero-py/.tox/py36/lib/python3.6/site-packages/ome...getHeaders\n    rv = self.storage.cols(None, current)\nAttributeError: \'NoneType\' object has no attribute \'cols\'\n'
    def exc_handler(*args, **kwargs):
        try:
            self = args[0]
            log.info(" Meth: %s.%s", self.__class__.__name__, func.__name__)
            rv = func(*args, **kwargs)
            log.info(__RESULT, rv)
            return rv
        except Exception as e:
            log.info(__EXCEPT, e)
            if isinstance(e, omero.ServerError):
                raise
            else:
                log.warn(
                    "%s raised a non-ServerError (%s): %s", func, type(e), e)
                msg = traceback.format_exc()
>               raise omero.InternalException(msg, None, "Internal exception")
E               omero.InternalException: exception ::omero::InternalException
E               {
E                   serverStackTrace = Traceback (most recent call last):
E                 File "/home/travis/build/ome/omero-py/.tox/py36/lib/python3.6/site-packages/omero/util/decorators.py", line 69, in exc_handler
E                   rv = func(*args, **kwargs)
E                 File "/home/travis/build/ome/omero-py/.tox/py36/lib/python3.6/site-packages/omero/util/decorators.py", line 40, in handler
E                   rv = func(*args, **kwargs)
E                 File "/home/travis/build/ome/omero-py/.tox/py36/lib/python3.6/site-packages/omero/tables.py", line 205, in getHeaders
E                   rv = self.storage.cols(None, current)
E               AttributeError: 'NoneType' object has no attribute 'cols'
E               
E                   serverExceptionClass = None
E                   message = Internal exception
E               }
.tox/py36/lib/python3.6/site-packages/omero/util/decorators.py:80: InternalException
```</details>

**Comment by joshmoore** [comment]
LGTM (but why is Py38 so fast?!)

Screen Shot 2020-07-10 at 09 48 52

**Pull request merged**
