### PR TITLE
Remove pytest-sugar (incompatible pytest change)

### PR DESCRIPTION
**Pull request by manics**
Same as https://github.com/ome/omero-web/pull/152/

See for example error on https://github.com/ome/omero-py/pull/195#issuecomment-600190406

### CODE REVIEW

**Comment by joshmoore** [comment]
One job failed and I can't restart.

**Comment by jburel** [comment]
restarted it

**Comment by jburel** [comment]
Problem of synchronization. Travis is green but no green tick on the PR

**Comment by joshmoore** [comment]
Something's still look quite wrong, but I couldn't find any recent `pytest-*` issues.

**Comment by manics** [comment]
Could it be this not-at-all recent issue and it just so happens a change somewhere has caused it? https://github.com/pytest-dev/pytest/issues/5502

**Comment by joshmoore** [comment]
Ah, seealso: https://github.com/ome/omero-py/issues/12

**Comment by joshmoore** [comment]
Still no luck with `-s` from https://github.com/albertvillanova/WikidataBot/issues/4

**Comment by joshmoore** [comment]
```
run-test: commands[0] | ulimit -n
256
```

**Comment by will-moore** [comment]
Looks good (green!).
Would be great to get this in and hopefully that'll fix travis in https://github.com/ome/omero-py/pull/195

**Pull request merged**
