### PR TITLE
Activate all tests

### PR DESCRIPTION
**Pull request by joshmoore**
Remaining failing tests will need to be marked with "broken"
(or alternatively, "skip").

### CODE REVIEW

**Comment by joshmoore** [comment]
```
         - test/unit/test_rtypes.py:468 TestModel.testMoreConversions[data2]
         - test/unit/tablestest/test_hdfstorage.py:307 TestHdfList.testLocking
         - test/unit/tablestest/test_hdfstorage.py:210 TestHdfStorage.testGetSetMetaMap
```

**Comment by joshmoore** [comment]
Python 3 now green. List on Python 2 is longer:

```
         - test/unit/test_rtypes.py:278 TestModel.testPassThroughNoneAndRTypes
         - test/unit/test_rtypes.py:262 TestModel.testGetAttrWorks
         - test/unit/test_rtypes.py:362 TestModel.testUnwrap
         - test/unit/test_rtypes.py:57 TestModel.testObjectCreationEqualsAndHash
         - test/unit/tablestest/test_servants.py:269 TestTables.testTablesIGetDirGetsRepoThenNoSF
         - test/unit/tablestest/test_servants.py:275 TestTables.testTablesIGetDirGetsRepoGetsSFCantFindRepoFile
         - test/unit/tablestest/test_servants.py:279 TestTables.testTablesIGetDirGetsRepoGetsSFCantFindRepoObject
         - test/unit/tablestest/test_servants.py:290 TestTables.testTables
         - test/unit/tablestest/test_servants.py:322 TestTables.testTablePreInitialized
         - test/unit/tablestest/test_servants.py:333 TestTables.testTableModifications
         - test/unit/tablestest/test_servants.py:285 TestTables.testTablesIGetDirGetsRepoGetsSFGetsRepo
         - test/unit/tablestest/test_servants.py:343 TestTables.testTableAddData
         - test/unit/tablestest/test_servants.py:370 TestTables.testErrorInStorage
         - test/unit/tablestest/test_servants.py:384 TestTables.testErrorInGet
         - test/unit/tablestest/test_servants.py:359 TestTables.testTableSearch
         - test/unit/tablestest/test_servants.py:265 TestTables.testTablesIGetDirNoRepoCreated
```

**Comment by joshmoore** [comment]
Green (even on py2 :wink:)

**Comment by sbesson** [comment]
In terms of coverage, without this PR 

```
========== 1109 passed, 152 skipped, 1 xfailed, 12 warnings in 31.18s ==========
```

With this PR

```
Results (45.88s):
    1173 passed
       1 xfailed
     152 skipped
```

Off-hand I do not see any problem with either commits so proposing to get a final code review and merge once validated by the integration tests.
May I also offer 997c8d07bb28620a9f20e0b9fe1619843b04f186 as an additional cleanup of the pytest warnings?

**Comment by joshmoore** [comment]
Done and expanded :smile:

**Comment by sbesson** [comment]
Note the tables unit tests are intermittently failing on Python 3.7 with the tables service returning a `null` proxy. We might need to selectively `xfail/skip` this test and come back to it as it probably highlights a 3.7-specific bug

**Pull request merged**
