### PR TITLE
Add show-uuid option to sessions who

### PR DESCRIPTION
**Pull request by chris-allan**
Adds a `--show-uuid` option to sessions who

### CODE REVIEW

**Comment by jburel** [comment]
I noticed that the info was available in the deprecated method ``omero sessions list`` but not in the recommended method ``omero sessions who`` when reviewing some of @mtbc work.
We discussed adding it later on. 
Thanks

**Comment by chris-allan** [comment]
Thanks, @jburel.

`sessions list` applies to sessions visible to the OMERO CLI whereas `sessions who` is querying the server for all the active sessions. Not sure what you mean by deprecated.

**Comment by jburel** [comment]
apologies I meant ``omero admin sessionlist``

**Comment by chris-allan** [comment]
Anything else from `omero admin sessionlist` we want to bring over?

/cc @joshmoore, @mtbc, @manics

**Comment by jburel** [comment]
Looking at the field: the  ``id`` was the only one missing 
```node | session                              | started                  | owner  | agent          | notes   ```
notes indicate if it the current session but this is now indicated using ``*``

**Comment by chris-allan** [comment]
I guess just `node`? Not sure that's important information at all. Maybe in a case where there are multiple nodes off the same database? Seems like a big edge case that while theoretically possible is almost never a reality.

**Comment by chris-allan** [comment]
@jburel: Can we get this merged or is there something else we need to do?

**Comment by jburel** [comment]
Thanks for the reminder. I forgot about it while on the road. 
Merging so it can be included in the coming release. @manics will re-run the script for changelog

**Pull request merged**
