### PR TITLE
Add support for Python 3.11

### PR DESCRIPTION
**Pull request by sbesson**
Python 3.11 has been released over a year ago and is available across several operating systems. This PR includes a minimal set of changes allowing OMERO.py to be functinal with Python 3.11. 

## Summary of changes

The biggest impact of the Python 3.11 was found to be in the dependencies of OMERO.py rather than the codebase itself

- e1d0fa409ce23597ad0338850d09368b49350baa adds the Python 3.11 manylinux wheel package to the Tox framework and adds the `py311` environment to `tox.ini` and the GitHub workflow definition to allow the testing under Python 3.11
- the vendored fork of `path.py` uses the "universal newline" opening mode `open(<file>, 'U')` deprecated in Python 3.3. and removed in Python 3.11 [^1] . Eventually, there is probably a larger concerted effort to remove the usage of this fork in favor of `pathlib` available from the standard library. Within the context of this work, this was assessed to be a larger body of work. Instead e1d0fa409ce23597ad0338850d09368b49350baa simply adjusts `omero_ext/path.py` to use `r` since "universal newline" mode is used by default since Python 3.
- the `mox3` dependency [^2] used by the unit tests was an unofficial port of the Google mox framework to Python 3. This library is unmaintained, has seen no releases since 3+ years and its usage was found to be incompatible with some of the Python 3.11 changes. 614a2e2cb0904fe9514353281d9bd1a0bd23a8a5 deprecates its usage in `testlib` and 986aa8421d09b6fbfb7339837b27f0b23ac60cec adjusts several tests to use `pytest-mock`  [^3], a thin-wrapper of the `mock` library available under the standard Python library

## Testing

With this PR included, all CI builds and tests should keep passing. In addition, tt should be possible to use OMERO.py as a client as well as deploying OMERO.server in a Python 3.11 virtual environment.

## Impact & open questions

- 614a2e2cb0904fe9514353281d9bd1a0bd23a8a5 directly impacts OMERO.py integration tests maintained under https://github.com/ome/openmicroscopy. If no objection, I can open a companion Pull Request with the corresponding adjustments to use `pytest-mock`. Unlike the GitHub worklow builds, this might require additional infrastructure work to install the new dependency in the Jenkins CI environment where the integration tests are executed
- `test/unit/clitest/test_admin.py` is still making heavy internal use of `mox3` to test the `omero admin` subcommands. These tests are currently skipped in the GitHub workflow as they require 1- a valid OMERO.server environment referred by `OMERODIR`, 2- Java installed. The re-activation of these tests has been captured in [^4]. In the context of this work, I see three options:
  1. maintain the statu quo and keep the unit tests untested for years (and might not even work anymore)
  2. migrate these tests to `ome/openmicroscopy` so that they are executed in a valid environment
  3. keep these tests in `omero-py` possibly looking into a more extensive usage of Python `mock` library to remove the dependency on Java and maybe a valid server binary
  I'll hold off on any work on the above until we reach a consensus.

[^1]: https://docs.python.org/3/whatsnew/3.11.html#porting-to-python-3-11
[^2]: https://pypi.org/project/mox3/
[^3]: https://pytest-mock.readthedocs.io/en/latest/
[^4]: https://github.com/ome/omero-py/issues/61

### CODE REVIEW

**Comment by jburel** [comment]
>
https://github.com/ome/omero-py/commit/614a2e2cb0904fe9514353281d9bd1a0bd23a8a5 directly impacts OMERO.py integration tests maintained under https://github.com/ome/openmicroscopy. If no objection, I can open a companion Pull Request with the corresponding adjustments to use pytest-mock. Unlike the GitHub worklow builds, this might require additional infrastructure work to install the new dependency in the Jenkins CI environment where the integration tests are executed

I will make sense to adjust the tests under https://github.com/ome/openmicroscopy
see 
```
components/tools/OmeroFS/test/drivers.py:from mox3 import mox
components/tools/OmeroPy/setup.py:    tests_require=['pytest', 'pytest-xdist', 'mox3'])
components/tools/OmeroPy/test/integration/clitest/cli.py:from mox3 import mox
components/tools/OmeroPy/test/integration/clitest/test_db.py:from mox3 import mox
```
The ``OMERO-test-integration`` job will need to be adjusted.

Regarding the test mentioned above ``test/unit/clitest/test_admin.py``. The tests could probably be migrated under https://github.com/ome/openmicroscopy. Outside the scope of this PR

**Comment by jburel** [comment]
``mox3`` should also be removed from https://github.com/ome/omero-py/blob/d22225fb21994e53569e9eab162eae29402b4b6d/docs/conf.py#L61

**Comment by jburel** [comment]
We have several repositories using ``mox3``. Is the idea to dispatch the work e.g. ``omego, scc, cli-render``?

**Comment by jburel** [comment]
``    tests_require=[
        'pytest',
        'mox3',
    ],``
in ``setup.py`` will need to be adjusted accordingly

**Comment by sbesson** [comment]
> It will make sense to adjust the tests under https://github.com/ome/openmicroscopy. 

Opened as https://github.com/ome/openmicroscopy/pull/6369. I can open associated devspace PRs if needed but eventually defer to you guys on when/how these changes should be integrated into the CI environment.

> We have several repositories using mox3 e.g. omego, scc, cli-render. Is the idea to dispatch the work?

The primary intent was to have OMERO working on Python 3.11. The `mox3` removal really comes as a requirement as soon as tests are executed against Python 3.11 but I can certainly look into auditing the OMERO plugin repositories as I expect the changes are minimal.
`omego` and `scc` are outside this scope of this work from my side.

**Comment by jburel** [comment]
Regarding ``devspace``, i will update my working branch (rocky9 support) which is what we are moving towards

**Comment by sbesson** [comment]
>     tests_require=[ 'pytest', 'mox3', ], in setup.py will need to be adjusted accordingly

As shown by the builds of https://github.com/ome/omero-py/pull/385/commits/8360c3fc1772875021c17dbc41dc7174362e417f, an unfortunate side-effect is that the `omero admin` unit tests currently skipped by GitHub Actions and discussed in the description of this PR  depended on `mox3` for the `MockCLI` class.

https://github.com/ome/omero-py/pull/385/commits/d378c3907d322eece79b07713b77792d97156fa0 tackles the problem by rewriting these tests to use the mock package and get rid entirely of `test/unit/clitest/mocks.py`. These tests are passing in my local environment so hopefully they are in much better place to be migrated into the appropriate location as a follow-up of this work.

**Comment by jburel** [comment]
Note that [b4a5342](https://github.com/ome/omero-py/pull/385/commits/b4a53421911afc407cf1d56ea826669ff1b6f471) is required to get the test green in omero-web with Python 3.11 cc @knabar

**Review by will-moore — APPROVED** [review]
LGTM 👍

**Pull request merged**
