### PR TITLE
changelog: list breaking changes

### PR DESCRIPTION
**Pull request by joshmoore**
- [x] getFileInChunks
 - [x] exportOmeTiff
 - [x] BytesIO etc.
 - [x] rlongs

cc: @ome/python

### CODE REVIEW

**Comment by will-moore** [comment]
```image.exportOmeTiff()```

**Comment by will-moore** [comment]
Previously where you did:
```
image = conn.getObject("Image", id)
Image.open(StringIO(image.renderJpeg))
```
now you need to do:
```
Image.open(BytesIO(image.renderJpeg))
```
That's not so much a BlitzGateway change, since it's just returning ```re.renderCompressed()```

**Comment by joshmoore** [comment]
Agreed. I think we add BytesIO, `str.decode()` etc to a more general migration guide as opposed to our own CHANGELOG.

**Comment by will-moore** [comment]
```conn.createOriginalFileFromFileObj()``` needs to take ```BytesIO``` file object instead of StringIO.

**Comment by will-moore** [comment]
Do we want to mention ```omero_type(longValue) and omero.rtypes.wrap(longValue)``` won't return ```rlong```?

**Comment by joshmoore** [comment]
Merging after a quick sign-off for posting on image.sc. Happy to have follow-ups. thanks, @will-moore.

**Pull request merged**
