### PR TITLE
Attempt to fix Travis builds

### PR DESCRIPTION
**Pull request by manics**
Upgrades all components

### CODE REVIEW

**Comment by joshmoore** [comment]
@manics : can you explain your thinking on the eager upgrade strategy? Is this something where we should be testing both variants?

**Comment by manics** [comment]
It was suggested as a workaround for Travis failures in https://github.com/jaraco/skeleton/commit/172c52b03a77e70e92a1ee491b059464e938fde3

**Comment by joshmoore** [comment]
Did you try limiting this to just `virtualenv`? I don't know the graph of what these 4 libraries will pull in, and I certainly don't use `upgrade-strategy` regularly enough (tip: I didn't know it existed) to ensure that what we're testing in travis would match what a user would see.

**Comment by manics** [comment]
Just tried it in the last commit, seems to work

**Comment by joshmoore** [comment]
LGTM :+1:

**Pull request merged**
