### PR TITLE
fix logging attribute error

### LINKED ISSUE #225: Potential AttributeError in SessionsStore.create
I'm not sure what the best way to fix this is (without potentially breaking other stuff you depend on), but there is an assumption being made in `SessionsStore.create()` that a `self.ctx` attribute has been injected into the object "somewhere" else:

https://github.com/ome/omero-py/blob/8d711f577d1000aad49ea794324b49450c952878/src/omero/util/sessions.py#L406-L410

If you create an unowned store, and try `store.create()` but hit an exception when [submitting the `TimeoutRequest`](https://github.com/ome/omero-py/blob/8d711f577d1000aad49ea794324b49450c952878/src/omero/util/sessions.py#L404), then the exception is not handled correctly.

### PR DESCRIPTION
**Pull request by tlambert03**
one possible solution that fixes #225 but still lets you log from `self.ctx` if you want.  Or just let me know if you want to ditch self.ctx altogether.

### CODE REVIEW

**Comment by joshmoore** [comment]
I'd err on the side of ditching. This class should really have no concept of `self.ctx` (That's a purely CLI thing.) Looking at this, I think this should also be a warn. The user has requested a timeout, and if that can't be set (or is incorrect) it seems like at least a WARN. (Perhaps the exception should even be thrown, but I'll need to review more for that.)

**Comment by tlambert03** [comment]
k, happy to convert to a warn or raise.  just let me know.

**Comment by joshmoore** [comment]
Let's go with a warn and get it released, then I can follow up with the rest.

**Comment by tlambert03** [comment]
k, do you want the formatted traceback in the warning?

**Comment by joshmoore** [comment]
Sorry for being a pain, @tlambert03, but can we go back to 2d34519dd2d7338b0bf5e47762ff6c4988653175 and:

 - keep the CmdError / Exception split,
 - use logger.warn for the CmdError at `WARN`, and
 - use logger.error for the catch-all Exception?

**Comment by tlambert03** [comment]
ok have another look at your convenience.  if you also wanted the `self.ctx` check added back, lemme know.

**Comment by joshmoore** [comment]
> ok have another look at your convenience.

Awesome, thank you!


> if you also wanted the `self.ctx` check added back, lemme know.

Nah. That should have never happened. :+1:

**Pull request merged**
