### PR TITLE
Update changelog and version for 5.6.1

### PR DESCRIPTION
**Pull request by manics**
Changelog notes mostly generated from https://gist.github.com/manics/383b4481e1c3a193d224016b01a5d52a

### CODE REVIEW

**Comment by jburel** [comment]
Side note: The gist will be useful to have in a central place considering the number of repository we have to handle,
This also means that as a team we need to work on the PR title a bit more

**Comment by manics** [comment]
I assume @joshmoore has something that he used for the last update

**Comment by joshmoore** [comment]
I have previous just used `git log --oneline --first-parent`. @chris-allan has suggested using github_changelog_generator. Regardless of which technique, I'm very much for our PR titles being end-user consumable.

**Comment by jburel** [comment]
Changes look good
Please do go ahead.

**Comment by jburel** [comment]
Thanks @manics

**Comment by jburel** [comment]
Travis is green. Merging and tagging

**Pull request merged**
