### PR TITLE
Deprecate duplicate plugin

### PR DESCRIPTION
**Pull request by sbesson**
As work has restarted on the decoupled https://github.com/ome/omero-cli-duplicate/ plugin, this formally deprecates the legacy code in `omero-py` using the similar strategy as #124. The plugin can then safely be dropped in omero-py 6.

This PR should be tested in two environment

-  omero-py alone

```
python3 -m venv venv
venv/bin/pip install git+git://github.com/snoopycrimecop/omero-py@merge_ci#egg=omero-py
venv/bin/omero duplicate -h # should fail
OMERO_DEV_PLUGINS=true venv/bin/omero duplicate -h # should display the help
OMERO_DEV_PLUGINS=true venv/bin/omero duplicate Dataset:50 # should display a deprecation warning
```

-  omero-py with omero-cli-duplicate plugin installed

```
python3 -m venv venv
venv/bin/pip install git+git://github.com/snoopycrimecop/omero-py@merge_ci#egg=omero-py
venv/bin/pip install git+git://github.com/snoopycrimecop/omero-cli-duplicate@merge_ci#egg=omero-cli-duplicate
venv/bin/omero duplicate -h # should display the help message
venv/bin/omero duplicate Dataset:50 # should duplicate without warnings
```

### CODE REVIEW

**Comment by sbesson** [comment]
In addition to the manual testing above, I suspect this deprecation should allow https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/ to properly install and test the recent `omero-cli-duplicate` improvements

**Comment by will-moore** [comment]
Testing `omero-py` alone I don't see a deprecation warning with:
```
$ OMERO_DEV_PLUGINS=true venv/bin/omero duplicate Dataset:232
Using session for will@localhost:4064. Idle timeout: 10 min. Current group: Lab Data
omero.cmd.Duplicate Dataset:232 ok
```

**Comment by sbesson** [comment]
Ah. My changes might only apply in the case of a detailed report. Does `$ OMERO_DEV_PLUGINS=true venv/bin/omero duplicate Dataset:232 --report` display the warning?

**Comment by will-moore** [comment]
Sorry - I had just installed `omero-cli-duplicate` into that venv to test part 2 (I'll uninstall in a sec).
But first I tried this (same empty Dataset as I used above):
```
$ venv/bin/omero duplicate Dataste:232
Using session for will@localhost:4064. Idle timeout: 10 min. Current group: Lab Data
omero.cmd.Duplicate Dataste:232 failed: 'graph-fail'
	message=
	stacktrace=java.lang.NullPointerException
	at java.base/java.lang.Class.isAssignableFrom(Native Method)
	at omero.cmd.graphs.GraphHelper.getTargetMultimap(GraphHelper.java:196)
	at omero.cmd.graphs.DuplicateI.step(DuplicateI.java:669)
	at omero.cmd.HandleI.steps(HandleI.java:448)
```

**Comment by will-moore** [comment]
oops - typo! Sorry

**Comment by will-moore** [comment]
Yes:
```
$ OMERO_DEV_PLUGINS=true venv/bin/omero duplicate Dataset:232 --report
Using session for will@localhost:4064. Idle timeout: 10 min. Current group: Lab Data
omero.cmd.Duplicate Dataset:232 ok
Steps: 8
Elapsed time: 0.038 secs.
Flags: []
This plugin is deprecated as of OMERO 5.8.0. Use the plugin available from https://pypi.org/project/omero-cli-duplicate/ instead.
Duplicates
  Dataset:1155
```

**Comment by will-moore** [comment]
With the plugin installed, duplicate works without warning message. 👍

**Comment by sbesson** [comment]
Cheers. Let me push another commit so that the warning message is displays on every invocation of the command

**Comment by will-moore** [comment]
Works for me now, testing locally...

```
$ OMERO_DEV_PLUGINS=true venv/bin/omero duplicate Dataset:232
This plugin is deprecated as of OMERO.py 5.8.0. Use the plugin available from https://pypi.org/project/omero-cli-duplicate/ instead.
Previous session expired for will on localhost:4064
Server: [localhost:4064] 
Username: [will]
Password:
Created session for will@localhost:4064. Idle timeout: 10 min. Current group: Lab Data
omero.cmd.Duplicate Dataset:232 ok
```

**Review by will-moore — APPROVED** [review]

**Comment by mtbc** [comment]
[OMERO-test-integration](https://latest-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/) is failing, maybe we need to decide about the `pip install omero-cli-duplicate` for devspaces.

**Comment by sbesson** [comment]
Probably largely depends on where the integration test for the new `omero-cli-duplicate` functionalities:

- if the tests are in ome/openmicroscopy, then OMERO-test-integration should install `omero-cli-duplicate` and we can port the change made in merge-ci
- if the tests are in omero-cli-duplicate using omero-test-infra, then the upstream ome/openmicroscopy could be adjusted to either test the legacy plugin or removed

**Comment by mtbc** [comment]
The for-the-meantime-at-least decision seemed to be to have them in ome/openmicroscopy.

**Pull request merged**
